name: osmcode
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables"]
highlighter: rouge
gems:
    - jekyll-redirect-from
collections:
    - file_formats_manual
    - libosmium_manual
    - opl_file_format
    - osmium_concepts
    - osmium_tool_manual
