name: osmcode
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables"]
highlighter: rouge
gems:
    - jekyll-redirect-from
collections:
    - osmium_concepts
    - opl_file_format
